# Generated by Django 5.0.6 on 2024-07-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_mailingsettings_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(choices=[('Рассылка остановлена', 'Created'), ('Рассылка активна', 'In Processing'), ('Рассылка завершена', 'Completed')], default='Рассылка остановлена', max_length=20, verbose_name='статус рассылки'),
        ),
    ]
