# Generated by Django 5.0.6 on 2024-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_mailingsettings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(choices=[('Рассылка остановлена', 'Stopped'), ('Рассылка активна', 'In Processing'), ('Рассылка завершена', 'Completed')], default='Рассылка остановлена', max_length=20, verbose_name='статус рассылки'),
        ),
    ]
