# Generated by Django 5.0.6 on 2024-07-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sender',
            new_name='owner',
        ),
    ]
