# Generated by Django 5.0.6 on 2024-07-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_rename_sender_client_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_block_user', 'Может заблокировать пользователя')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
