# Generated by Django 5.0.6 on 2024-07-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_block_user', 'Может заблокировать пользователя')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
